const sentences = {
    Easy: [
        "The sun is shining brightly in the sky.",
        "I enjoy listening to music every day.",
        "She always wears a beautiful red dress.",
        "The dog loves playing fetch with a ball.",
        "He dances gracefully on the stage.",
        "They planted colorful flowers in the garden.",
        "We went for a relaxing walk by the beach.",
        "The movie was funny and entertaining.",
        "The book has an exciting plot with unexpected twists.",
        "The children are playing happily in the park.",
    ],
   Medium: [
        "Yesterday, I went to the park and played soccer with my friends. We had a great time and then had a delicious meal at a nearby restaurant.",
        "She prepared a delicious dinner for the whole family. The meal included various dishes, and everyone praised her culinary skills.",
        "The museum had an impressive collection of ancient artifacts. The exhibits showcased the rich history of the region and its cultural heritage.",
        "During the summer vacation, they visited various historical sites. They learned about the past and experienced the beauty of different places.",
        "Learning a new language can be challenging but rewarding. It opens up opportunities to connect with people from diverse backgrounds.",
        "The concert lasted for more than two hours and had amazing performances. The audience was captivated by the talented musicians.",
        "After a long day at work, he likes to relax and watch movies. It helps him unwind and escape from the stress of daily life.",
        "They hiked through the forest, enjoying the fresh air and beautiful scenery. The peaceful environment brought them a sense of tranquility.",
        "In the science lab, they conducted several interesting experiments. The results provided valuable insights for their research.",
        "The team worked together to complete the project on time. Their collaboration and dedication ensured its success.",
    ],
    Hard: [
        "The marathon runners endured the scorching sun as they approached the finish line. Every step felt like a test of their willpower and determination. They pushed their bodies to the limit, ignoring the pain and fatigue.",
        "The intricate details of the ancient architecture fascinated the historians. Each building told a story of the past, and the researchers were eager to decipher its secrets. The ruins held clues to a forgotten civilization.",
        "The scientist presented a groundbreaking theory that challenged existing beliefs. The scientific community was divided, with some embracing the new ideas and others skeptical. The debate sparked a revolution in the field.",
        "She eloquently delivered a speech on climate change and its consequences. Her words resonated with the audience, inspiring them to take action and protect the planet. The call for environmental responsibility grew stronger.",
        "After months of preparation, they finally launched the ambitious space mission. The astronauts embarked on a journey to explore distant planets, taking humanity one step closer to understanding the universe.",
        "The artist meticulously painted a masterpiece that captured the essence of nature. Each brushstroke conveyed emotion and beauty, making the artwork timeless. Art enthusiasts praised the painter's skill and creativity.",
        "The detective carefully examined the crime scene for any potential clues. Every detail mattered as they pieced together the puzzle of the crime. The pursuit of justice was relentless and unwavering.",
        "The mathematician worked tirelessly to solve the complex equation. Days turned into nights as they delved deeper into the problem. The eureka moment brought a sense of triumph and intellectual satisfaction.",
        "The symphony orchestra delivered a mesmerizing performance to a captivated audience. The music swelled and soared, evoking a range of emotions. Applause filled the concert hall as the musicians took their final bow.",
        "The negotiation process between the two countries required patience and diplomacy. Tensions were high, but both sides sought a peaceful resolution. The diplomats worked tirelessly to find common ground.",
    ],
};

export default sentences